spawn:
  world: world
  x: 0.5
  y: 64.0
  z: 0.5
  yaw: 0.0
  pitch: 0.0

npcs:
  relicwars_1v1:
    queue: RELICWARS_1V1
    skin: corwis
    name: "RelicWars 1v1"
    world: world
    x: -6.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  relicwars_8x2:
    queue: RELICWARS_8X2
    skin: corwis
    name: "RelicWars 8x2"
    world: world
    x: -4.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  relicwars_3v3v3v3:
    queue: RELICWARS_4X3
    skin: corwis
    name: "RelicWars 3v3v3v3"
    world: world
    x: -2.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  relicwars_4v4v4v4:
    queue: RELICWARS_4X4
    skin: corwis
    name: "RelicWars 4v4v4v4"
    world: world
    x: -0.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  showdown_solo:
    queue: SHOWDOWN_SOLO
    skin: corwis
    name: "Showdown Solo"
    world: world
    x: 1.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  showdown_duo:
    queue: SHOWDOWN_DUO
    skin: corwis
    name: "Showdown Duo"
    world: world
    x: 3.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0
  showdown_4er:
    queue: SHOWDOWN_4ER
    skin: corwis
    name: "Showdown 4er"
    world: world
    x: 5.5
    y: 64.0
    z: 0.5
    yaw: 0.0
    pitch: 0.0

builder:
  velocity-server-name: "builder-1"
  pelican-url: "http://49.13.1.183:8080"
  api-key: ""
  server-uuid: ""
  redis:
    host: "172.18.0.1"
    port: 6379
    password: ""
